version: "3.8"

services:
  # Nuxt 3 App
  nuxt-app:
    build: .
    container_name: nuxt_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:root@localhost:3306/Store
    volumes:
      - .:/app
      - /app/node_modules

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Store
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
